# Generated by Django 3.2.7 on 2021-11-09 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destaque',
            name='nome',
            field=models.CharField(default=datetime.date, max_length=100),
            preserve_default=False,
        ),
    ]
